import Link from "next/link"

export const metadata = {
  title: 'login',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div >
      {children}
      <Link href={"/"}>go back</Link>
    </div>
  )
}
